### ISSUE TITLE
Scripts don’t get installed?

### ISSUE THREAD

**Issue by ap** [Corion/Net-Fritz-Phonebook#1]
There’s no `EXE_FILES` section in your Makefile.PL so the user has to dig the scripts out of the tarball separately… is that intentional? (And if so… can I request making a separate App:: out of them maybe?)

**Comment by Corion** [comment]
Not installing them was partially intentional as their prerequisites aren't listed (Net::CalDAV) and need to be installed separately.

Spinning the scripts into their own distributions makes much sense and I plan on moving them over.

**Comment by Corion** [comment]
Now the scripts live in https://github.com/Corion/App-Fritz-Import-CardDAV , even though that isn't a full CPAN distribution yet. At least it lists the rough prerequisites.
