### ISSUE TITLE
Deleting an entry deletes the wrong entry

### ISSUE THREAD

**Issue by sciurius** [Corion/Net-Fritz-Phonebook#2]
The following snippet:

    my $entry = $phonebooks[0]->get_entry_by_uniqueid(1201);
    printf( "%4d: %4d %s %s %s\n",
	    $entry->uniqueid,
	    $entry->phonebookIndex,
	    $entry->category,
	    $entry->name,
	    join(",", map { $_->content } @{$entry->numbers}),
	  );
    $entry->delete;

This prints the data for entry with uniqueId 1201. In my particular case, this entry has phonebookIndex 26. After the `delete` is executed, entry with uniqueId 1201 still exists in the phonebook, but an unrelated entry (uniqueId 1101, phonebookIndex 31) is deleted instead.

The reason seems to be that, when retrieving all entries, or using get_entry_by_uniqueid, internal entries (e.g. `**601`) are included in the list (and occupy index numbers) while get_entry_by_index (and delete **!**) do _not_ take these internal entries into account.

Ironically, when get_entry_by_index is used, the PhonebookEntry retrieved does _not_ have its phonebookIndex set and hence it cannot be deleted unless you set the index manually.

And yes, entry index numbers are updated after each delete.

**Comment by sciurius** [comment]
The following replacement for `Net::Fritz::PhonebookEntry::delete` uses the `uniqueid` property for deletion, thus eliminating all problems described in the previous message.

    sub delete( $self, %options ) {
	my $res = $self->phonebook->service->call('DeletePhonebookEntryUID',
	    NewPhonebookID => $self->phonebook->id,
	    NewPhonebookEntryUniqueID => $self->uniqueid,
	);

	croak $res->error
	    if $res->error;

	$res->data
    }

**Comment by Corion** [comment]
Whoops! I hope you didn't lose data through that!

Thank you very much for the code! I'll release an updated version soonish.

**Comment by sciurius** [comment]
Thanks. Please note that that UniqueUID arguments were added in 2018-06-05 so it probably requires version 7 and up.

**Comment by Corion** [comment]
I've now added a binary search for the versions where `DeletePhonebookEntryUID` is unavailable. I can't test the new version, since I don't have `DeletePhonebookEntryUID` available, but hopefully it will work.

**Comment by Corion** [comment]
This is now released as version 0.04 - if this fix works on FritzOS 7+ , please close the issue. If not, please update the issue :-D

**Comment by sciurius** [comment]
Checked on 7.13 and it seems to work properly. Thanks!
