### ISSUE TITLE
Add XML declaration for SetPhonebookEntry

### ISSUE THREAD

**Issue by sciurius** [Corion/Net-Fritz-Phonebook#3]
To get non-ASCII characters inserted correctly, I needed to add an explicit XML declaration to the XML passed to the SetPhonebookEntry service. This can be obtained by adding `XMLDecl => 1` to the XMLout call.

    sub add_entry( $self, $entry ) {
        my $s = $entry->build_structure;

        my $xml = XMLout({ contact => [$s]}, XMLDecl => 1);
        #use Data::Dumper;
        #$Data::Dumper::Useqq = 1;
    #    $xml =~ s; (quickdial|prio|vanity)="";;g;
    #    $xml =~ s;<category>0</category>;<category/>;g;
        #print Dumper \$xml;

        my $res = $self->service->call('SetPhonebookEntry',
            NewPhonebookID => $self->id,
            NewPhonebookEntryID => '', # new entry
            NewPhonebookEntryData => $xml,
        );
    };

Alternatively, insert the header explicitly:

        $xml = '<?xml version="1.0" encoding="utf-8"?>'."\n".$xml;

(This is what I prefer, since it includes the encoding.)
You may wish to add the two lines stripping `quickdial`, `prio` and `vanity` attributes from phone numbers and eliminating the setting of category `0`.

**Comment by Corion** [comment]
Thank you very much for diagnosing and fixing this!
