### ISSUE TITLE
Prevent dummy quickdial/vanity codes

### ISSUE THREAD

**Issue by sciurius** [Corion/Net-Fritz-Phonebook#4]
The XML to add a phone number uses the following number entity:

    <number prio="" vanity="" quickdial="">123456</number>

The empty vanity and quickdial attributes lead to dummy quickdial/vanity codes in the primary phone book. To avoid this, remove them from the XML, e.g.

    sub add_entry( $self, $entry ) {
        my $s = $entry->build_structure;

        my $xml = XMLout({ contact => [$s] }, XMLDecl => 1 );
        #use Data::Dumper;
        #$Data::Dumper::Useqq = 1;
        $xml =~ s; (quickdial|prio|vanity)="";;g;
        $xml =~ s;<category>0</category>;<category/>;g;
    #    use DDumper; DDumper \$xml;
        #print Dumper \$xml;

        my $res = $self->service->call('SetPhonebookEntry',
            NewPhonebookID => $self->id,
            NewPhonebookEntryID => '', # new entry
            NewPhonebookEntryData => $xml,
        );
    };

**Comment by Corion** [comment]
I've addressed that now by making those attributes optional and not outputting them in the first place. Let me know if that works for you!
